# Swagger Configuration
springdoc.swagger-ui.path=/swagger.html
springdoc.api-docs.enabled=true

# Server Configuration
server.port=8080

# Application
spring.application.name=portales

# MongoDB Database (MongoDB Atlas)
spring.data.mongodb.uri=mongodb+srv://kimberlingyactayo:QrPYtSU5PC3z2LGg@sentimentanalysis.wegpdti.mongodb.net/sentiment_mongo_db?retryWrites=true&w=majority&appName=portales

# Logging
logging.level.org.springframework.web=ERROR
logging.level.org.springframework.data.mongodb=TRACE
logging.level.org.mongodb.driver=DEBUG